# Generated by Django 5.0.7 on 2024-08-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_superuser_account_is_superadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
